
# open shell here
[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# close input with esc
[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"

# change seak from A-j/k to C-j/k
[[manager.prepend_keymap]]
on   = [ "<C-k>" ]
exec = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on   = [ "<C-j>" ]
exec = "seek 5"
desc = "Seek down 5 units in the preview"


# enter dir or open file with l
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# Bookmarks plugin
[[manager.prepend_keymap]]
on = [ "m" ]
exec = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
exec = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
exec = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
exec = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

# Something else
